// <auto-generated />
using System;
using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Server.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200310041148_Migration_002")]
    partial class Migration_002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Todo.Models.MemberEntity", b =>
                {
                    b.Property<Guid>("member_id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("birthday");

                    b.Property<DateTime?>("created_at");

                    b.Property<string>("email")
                        .HasMaxLength(255);

                    b.Property<string>("firstname")
                        .HasMaxLength(255);

                    b.Property<string>("lastname")
                        .HasMaxLength(255);

                    b.Property<string>("password")
                        .HasMaxLength(255);

                    b.Property<string>("sex")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("updated_at");

                    b.HasKey("member_id");

                    b.ToTable("member");
                });

            modelBuilder.Entity("Todo.Models.PermissionEntity", b =>
                {
                    b.Property<Guid>("permission_id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("created_at");

                    b.Property<Guid>("member_id");

                    b.Property<string>("permission_type")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("updated_at");

                    b.HasKey("permission_id");

                    b.HasIndex("member_id")
                        .IsUnique();

                    b.ToTable("permission");
                });

            modelBuilder.Entity("Todo.Models.PermissionEntity", b =>
                {
                    b.HasOne("Todo.Models.MemberEntity", "Member")
                        .WithOne("Permission")
                        .HasForeignKey("Todo.Models.PermissionEntity", "member_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
