// <auto-generated />
using System;
using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Server.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200311052846_Migration_003")]
    partial class Migration_003
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Todo.Models.BookCategoryEntity", b =>
                {
                    b.Property<Guid>("book_category_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("code")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("created_at");

                    b.Property<string>("name")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("updated_at");

                    b.HasKey("book_category_id");

                    b.ToTable("book_category");
                });

            modelBuilder.Entity("Todo.Models.BookEntity", b =>
                {
                    b.Property<Guid>("book_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("author")
                        .HasMaxLength(255);

                    b.Property<Guid>("book_category_id");

                    b.Property<DateTime?>("created_at");

                    b.Property<string>("detail")
                        .HasMaxLength(5000);

                    b.Property<string>("image")
                        .HasMaxLength(1000);

                    b.Property<string>("name")
                        .HasMaxLength(255);

                    b.Property<int>("number_of_page");

                    b.Property<string>("publisher")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("updated_at");

                    b.HasKey("book_id");

                    b.HasIndex("book_category_id");

                    b.ToTable("book");
                });

            modelBuilder.Entity("Todo.Models.MemberEntity", b =>
                {
                    b.Property<Guid>("member_id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("birthday");

                    b.Property<DateTime?>("created_at");

                    b.Property<string>("email")
                        .HasMaxLength(255);

                    b.Property<string>("firstname")
                        .HasMaxLength(255);

                    b.Property<string>("lastname")
                        .HasMaxLength(255);

                    b.Property<string>("password")
                        .HasMaxLength(255);

                    b.Property<string>("sex")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("updated_at");

                    b.HasKey("member_id");

                    b.ToTable("member");
                });

            modelBuilder.Entity("Todo.Models.PermissionEntity", b =>
                {
                    b.Property<Guid>("permission_id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("created_at");

                    b.Property<Guid>("member_id");

                    b.Property<string>("permission_type")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("updated_at");

                    b.HasKey("permission_id");

                    b.HasIndex("member_id")
                        .IsUnique();

                    b.ToTable("permission");
                });

            modelBuilder.Entity("Todo.Models.BookEntity", b =>
                {
                    b.HasOne("Todo.Models.BookCategoryEntity", "BookCategory")
                        .WithMany()
                        .HasForeignKey("book_category_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Todo.Models.PermissionEntity", b =>
                {
                    b.HasOne("Todo.Models.MemberEntity", "Member")
                        .WithOne("permission")
                        .HasForeignKey("Todo.Models.PermissionEntity", "member_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
