// <auto-generated />
using System;
using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Server.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("25620724102632_Migration001")]
    partial class Migration001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Todo.Models.LawsEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("created_at");

                    b.Property<Guid?>("created_by");

                    b.Property<DateTime?>("delete_at");

                    b.Property<bool?>("is_active");

                    b.Property<string>("name")
                        .HasMaxLength(255);

                    b.Property<string>("note")
                        .HasMaxLength(3000);

                    b.Property<DateTime?>("updated_at");

                    b.Property<Guid?>("updated_by");

                    b.HasKey("id");

                    b.ToTable("laws");
                });

            modelBuilder.Entity("Todo.Models.StaffEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ad_username")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("created_at");

                    b.Property<Guid?>("created_by");

                    b.Property<DateTime?>("delete_at");

                    b.Property<string>("email")
                        .HasMaxLength(255);

                    b.Property<string>("fullname")
                        .HasMaxLength(255);

                    b.Property<bool?>("is_active");

                    b.Property<string>("password")
                        .HasMaxLength(255);

                    b.Property<int>("position")
                        .HasMaxLength(255);

                    b.Property<string>("tel")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("updated_at");

                    b.Property<Guid?>("updated_by");

                    b.HasKey("id");

                    b.ToTable("staff");
                });
#pragma warning restore 612, 618
        }
    }
}
