// <auto-generated />
using System;
using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Server.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("25630222054150_Migration_001")]
    partial class Migration_001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Todo.Models.MemberEntity", b =>
                {
                    b.Property<Guid>("member_id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("birthday");

                    b.Property<DateTime?>("created_at");

                    b.Property<string>("email")
                        .HasMaxLength(255);

                    b.Property<string>("firstname")
                        .HasMaxLength(255);

                    b.Property<string>("lastname")
                        .HasMaxLength(255);

                    b.Property<string>("password")
                        .HasMaxLength(255);

                    b.Property<string>("sex")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("updated_at");

                    b.HasKey("member_id");

                    b.ToTable("member");
                });
#pragma warning restore 612, 618
        }
    }
}
